"""empty message

Revision ID: 07b776806365
Revises: a51fcc50b3b0
Create Date: 2023-05-02 14:21:27.662524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07b776806365'
down_revision = 'a51fcc50b3b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        #batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('parentID')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parentID', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'note', ['parentID'], ['id'])

    # ### end Alembic commands ###
