"""empty message

Revision ID: 19918adb7203
Revises: 07b776806365
Create Date: 2023-05-02 14:25:40.377876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19918adb7203'
down_revision = '07b776806365'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        #batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('parentID')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parentID', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'note', ['parentID'], ['id'])

    # ### end Alembic commands ###
