"""empty message

Revision ID: 8820c97cba1c
Revises: 58dad32c8e9e
Create Date: 2023-03-17 13:49:19.919517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8820c97cba1c'
down_revision = '58dad32c8e9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_note')
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_note_id'), ['id'])

    with op.batch_alter_table('taskList', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=32), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_taskList_id'), ['id'])
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_taskList_user_id_users'), 'users', ['user_id'], ['id'])
        batch_op.drop_column('author')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_users_id'), ['id'])
        batch_op.create_unique_constraint(batch_op.f('uq_users_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_username'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_users_id'), type_='unique')

    with op.batch_alter_table('taskList', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.VARCHAR(length=32), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_taskList_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['author'], ['id'])
        batch_op.drop_constraint(batch_op.f('uq_taskList_id'), type_='unique')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_note_id'), type_='unique')

    op.create_table('_alembic_tmp_note',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('number', sa.INTEGER(), nullable=True),
    sa.Column('list_id', sa.INTEGER(), nullable=True),
    sa.Column('text', sa.VARCHAR(length=250), nullable=True),
    sa.ForeignKeyConstraint(['list_id'], ['taskList.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', name='uq_note_id')
    )
    # ### end Alembic commands ###
