"""empty message

Revision ID: ff3f258bdca4
Revises: f8539f58be2d
Create Date: 2023-03-30 09:38:14.883864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff3f258bdca4'
down_revision = 'f8539f58be2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parentID', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_note_parentID_note'), 'note', ['parentID'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_note_parentID_note'), type_='foreignkey')
        batch_op.drop_column('parentID')

    # ### end Alembic commands ###
