"""empty message

Revision ID: 280a34045180
Revises: 5782f555a000
Create Date: 2023-03-17 13:37:35.174577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '280a34045180'
down_revision = '5782f555a000'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('taskList', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=32), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('author')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('taskList', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.VARCHAR(length=32), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['author'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
