"""Initial migration.

Revision ID: a7e5862a1a30
Revises: 
Create Date: 2023-03-03 10:41:20.565933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7e5862a1a30'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('last', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last')
        batch_op.drop_column('first')

    # ### end Alembic commands ###
