#!C:\Users\Technology Showcase\Desktop\Main_Checklist\OnboardingChecklist\onboarding-checklist\backend\env\Scripts\python.exe

import sys

if __name__ == "__main__":
    from EB.builder.eb_main import main
    sys.exit(main(sys.argv))
